### ISSUE TITLE
Feature Request: Override rate values

### ISSUE THREAD

**Issue by untemps** [untemps/read-per-minute#11]
To extend @webJose's work in this [PR](https://github.com/untemps/read-per-minute/pull/10), it can be useful to add the ability to override the default rate values for a particular instance.

In this case, we either add an argument in the constructor, or we add a `setRates` method (and a reset one), or both.

We should be careful with the type and the format of the constructor or method argument, especially the default value management (e.g. the `default` value does not exist among the custom values).

CAUTION: This will result in a breaking change. To check the existence of the lang set, we need to make the `isLangExist` dynamic

**Comment by webJose** [comment]
If the constructor parameter is optional, then there is no breaking change.  Also adding a new method is not a breaking change, so that would be nice, I suppose.

**Comment by untemps** [comment]
To override the rate values for a particular instance, we need to make the `isLangExist` method available at the instance level. Since this is currently a public static method, this change may break some usages.

**Comment by webJose** [comment]
Ah, ok.  I see.  I didn't realize that change. :-(

**Comment by untemps** [comment]
@webJose If you want to review the PR: #14
